# Generated by Django 4.2.16 on 2026-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="prescriptionitem",
            options={"ordering": ["tablet_name"]},
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("ALLERGY", "Allergy"),
                    ("IMMUNIZATION", "Immunization"),
                    ("PRESCRIPTION", "Prescription"),
                    ("LAB_REPORT", "Lab Report"),
                    ("DIAGNOSIS", "Diagnosis"),
                    ("DISCHARGE_SUMMARY", "Discharge Summary"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
